server:
  port: 8813

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?useUnicode=true&useSSL=true
    username: root
    password: lwy092721..
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: false

mybatis:
  typeAliasesPackage:
  mapperLocations: classpath:mapper/*.xml


